version: '3'
services:
  bitcoind:
    image: mocacinno/btc_testnet4:bci_node
    privileged: true
    container_name: bitcoind
    volumes:
      - /root/project/run_btc_testnet4/data:/root/.bitcoin/
    ports:
      - "8333:8333"
      - "48332:48332"
      - "5000:5000"
    command: bitcoind --testnet4 --server --rpcbind=0.0.0.0 --rpcuser=demo --rpcpassword=demo --rpcport=5000 --rpcallowip=53.38.0.0/16 --rpcallowip=172.0.0.0/8 --rpcallowip=127.0.0.1 --rpcallowip=10.8.0.0/16
    networks:
      - my_network

  cpuminer:
    image: mocacinno/btc_testnet4:bci_cpuminer
    container_name: cpuminer
    privileged: true
    command: cpuminer-x64 -a sha256d -o http://bitcoind:5000 -O demo:demo --coinbase-addr=tb1qumlhr8tn9gsdyujy464jkk4c5r488u8kxteyx5 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
