version: '3'
services:
  bitcoind:
    image: ghcr.io/mocacinno/btc_testnet4:latest
    privileged: true
    container_name: bitcoind
    volumes:
      - /root/project/run_btc_testnet4/data:/root/.bitcoin/
      - /root/project/run_btc_testnet4/lightning:/root/.lightning
    command: ["bitcoind", "-testnet4", "-server", "-rpcuser=demo", "-rpcpassword=demo", "-rpcallowip=127.0.0.1", "-rpcport=5000"]
    ports:
      - "8333:8333"
      - "48332:48332"
      - "5000:5000"
      - "19735:19735"
      - "3000:3000"
